### ISSUE TITLE
Connection Pool should allow disposing all connections

### ISSUE THREAD

**Issue by schveiguy** [vibe-d/vibe-core#101]
IMO, the whole point of using a connection pool is to both limit the number of concurrent connections, and avoid reconnecting every time you need one.

In my code, I'm leaving the connection to the database open so that I don't have to reconnect every time I fetch a locked connection.

The result of this is when my server shuts down, I get warnings about stale file descriptors. I'd like to close these open connections in a static destructor, but there is no mechanism to do this reliably! A `dispose` method would be really useful here. Or even a mechanism to iterate over all the allocated connections, as `ConnectionPool` doesn't really know how to use the `Connection`.

**Comment by s-ludwig** [comment]
Fixed by #143.

**Comment by s-ludwig** [comment]
For reference, related changes in the vibe.d repo: https://github.com/vibe-d/vibe.d/issues/2287
