### ISSUE TITLE
Ddox warnings causing major ddox issues

### ISSUE THREAD

**Issue by andre2007** [vibe-d/vibe-core#103]
Building ddox documentation fails due to ddox warnings in vibe-core

dub build -b ddox

Fetching botan-math 1.0.3 (getting selected version)...

Fetching vibe-core 1.4.4 (getting selected version)...

Fetching memutils 0.4.13 (getting selected version)...

Fetching taggedalgebraic 0.10.12 (getting selected version)...

Fetching vibe-d 0.8.4 (getting selected version)...

Fetching stdx-allocator 2.77.4 (getting selected version)...

Fetching botan 1.12.10 (getting selected version)...

Fetching diet-ng 1.5.0 (getting selected version)...

Fetching openssl 1.1.6+1.0.1g (getting selected version)...

Fetching eventcore 0.8.39 (getting selected version)...

Fetching mir-linux-kernel 1.0.1 (getting selected version)...

Fetching libevent 2.0.2+2.0.16 (getting selected version)...

Fetching libasync 0.8.3 (getting selected version)...

Performing "ddox" build using dmd for x86_64.

taggedalgebraic 0.10.12: building configuration "library"...

eventcore 0.8.39: building configuration "winapi"...

stdx-allocator 2.77.4: building configuration "library"...

vibe-core 1.4.4: building configuration "winapi"...

..\..\..\..\Users\D\AppData\Local\dub\packages\vibe-core-1.4.4\vibe-core\source\vibe\core\concurrency.d(1135,30): Warning: Ddoc: parameter count mismatch

..\..\..\..\Users\D\AppData\Local\dub\packages\vibe-core-1.4.4\vibe-core\source\vibe\core\taskpool.d(40,2): Warning: Ddoc: parameter count mismatch

dmd failed with exit code 1.

**Comment by s-ludwig** [comment]
Hm, I can't see what's wrong there. The parameter count seems to be identical in the doc comment and in the signature. Workaround would be to add `buildRequirements "allowWarnings"`, but it *looks* like this is a Ddoc bug in DMD.
