### ISSUE TITLE
TCPConnectionFunction is a delegate and not a function pointer

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe-core#109]
```d
/// Callback invoked for incoming TCP connections.
@safe nothrow alias TCPConnectionDelegate = void delegate(TCPConnection stream);
/// ditto
@safe nothrow alias TCPConnectionFunction = void delegate(TCPConnection stream);
```

This makes the `listenTCP_s` documentation stating that it accepts a function pointer wrong.

Is this intended? Would changing this break old code?

**Comment by Yoplitein** [comment]
Calling toDelegate with a delegate is a [no-op](https://github.com/dlang/phobos/blob/v2.084.1/std/functional.d#L1466). This seems like a mistake made when copy-pasting.
