### ISSUE TITLE
vibe.core.file recognize special files

### ISSUE THREAD

**Issue by FraMecca** [vibe-d/vibe-core#132]
I can't find a way to check if a file is a posix special file from a FileInfo structure.
std.file provides isFile and isDirectory and if they are both false the file is a special file.

**Comment by FraMecca** [comment]
PR was merged, documentation should be updated:
https://vibed.org/api/vibe.core.file/FileInfo

**Comment by s-ludwig** [comment]
Tagged 1.6.2 and incorporated it into the 0.8.5 vibe.d docs now.
