### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by SMietzner** [vibe-d/vibe-core#16]
Hi,
I read the readme.md to find out what vibe-core really does. I couldn't figure it out. 
Please consider adding a general description with goals, main features and maybe examples.

Thanx

SMietzner

**Comment by SMietzner** [comment]
Great! Now I (and other noobs) get it! Thanks for your effort!

**Comment by s-ludwig** [comment]
Thanks for taking the time to open an issue! These things are so easy to forget/overlook after while of being involved in a project.
