### ISSUE TITLE
Assertion failure in vibe.core.net.TCPConnection.waitForData

### ISSUE THREAD

**Issue by joseph-wakeling-frequenz** [vibe-d/vibe-core#167]
I'm getting the following assertion failure irregularly but consistently in a long-running server application that reads (and occasionally writes) continually via a TLS connection, receiving somewhere in the region of tens to hundreds of messages per second:

```
core.exception.AssertError@../../../.dub/packages/vibe-core-1.6.2/vibe-core/source/vibe/core/net.d(583): Assertion failure
```

... which corresponds to the following line in the `TCPConnection.waitForData` method (more specifically, in a callback it employs internally):
https://github.com/vibe-d/vibe-core/blob/v1.6.2/source/vibe/core/net.d#L583

Typically this occurs after the application has been running for some time (many hours, sometimes several days), but it's recurring enough to regularly bring down the app.

**Comment by Geod24** [comment]
@joseph-wakeling-frequenz : Is this still happening ?

If so, could you:
- Tell us what Vibe.d version you use ?
- Tell us what compiler and compilation arguments you use ?

Optionally, updating vibe-core might be a good idea.
Is your application using Threads ?

**Comment by joseph-wakeling-frequenz** [comment]
Hi @Geod24, thanks for checking in :-)

I'll probably be able to report back on whether it's still happening in a few weeks (sorry for the delay, it's unavoidable).

I believe the last library versions used/deployed were vibe-core 1.7.0 and vibe-d 0.8.6.  I assume you are curious about whether some of the fixes in vibe-core 1.7 and 1.8 (e.g. related to eventcore usage) might have addressed the issue?  Do you have any particular fixes in mind that I might be able to use for before/after comparison?

The project is built with LDC, using the compiler arguments of a standard `dub build`.  Off the top of my head I can't remember exactly which compiler version was used for the last deployment.

Threads are not used, at least not intentionally.

**Comment by joseph-wakeling-frequenz** [comment]
It's a bit of a late follow-up (the affected project was back-burner for a while) but having started work on it again, the exact same issue showed up again today:

This is with the app built with LDC 1.20.1 and LLVM 9.0.1, with the following library versions:

```
"eventcore": "0.9.6",
"libasync": "0.8.6",
"libevent": "2.0.2+2.0.16",
"vibe-core": "1.9.2",
"vibe-d": "0.8.6"
```

Error message:

```
core.exception.AssertError@../../../.dub/packages/vibe-core-1.9.2/vibe-core/source/vibe/core/net.d(605): Assertion failure
```

The line reference is the same check as in the original bug report (just on a later line now because of additions to the source file in newer vibe-core releases): https://github.com/vibe-d/vibe-core/blob/v1.9.2/source/vibe/core/net.d#L605

I haven't dived too deeply but it looks like the `AssertError` was actually caught by the vibe runtime somewhere (I presume by the scheduler, but haven't checked), which meant that the main running task actually unwound gracefully (e.g. I saw `scope (exit)` blocks being triggered).

**Comment by s-ludwig** [comment]
Not sure whether this is still relevant, but I've just fixed an issue that could manifest in this way: 307e4391d0a5590f40cb3189a9c2887569db3dcc

So calling `TCPConnection.close()` while still in `waitForDataEx` would previously reset `m_socket` to `StreamSocketFD.invalid`, causing the assertion condition to become false.

**Comment by s-ludwig** [comment]
Closing as probably fixed. #332 and #338 are to related followup fixes.
