### ISSUE TITLE
FileStream does not implement method read

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe-core#284]
when trying to compile my project depending on vibe-core I get the following error:

```
../../.dub/packages/vibe-core-1.18.0/vibe-core/source/vibe/internal/traits.d(392,2): Error: static assert:  "`FileStream` does not implement method `read` of type `@safe ulong(scope ubyte[] dst, IOMode mode)`"
```

I don't use FileStream knowingly (by name) so I don't know why this happens. With a little extension of the error message it becomes more obvious where the error is though:

```
../../.dub/packages/vibe-core-1.18.0/vibe-core/source/vibe/internal/traits.d(392,2): Error: static assert:  "`vibe.core.file.FileStream` does not implement method `read` of type `ulong(scope ubyte[], eventcore.driver.IOMode) @safe` from `vibe.core.stream.RandomAccessStream`"
```

so it seems like the read method isn't `scope` on the first parameter in `vibe.core.file.FileStream`

**Comment by Geod24** [comment]
Are you using `-dip1000` ?

**Comment by WebFreak001** [comment]
with `dub -v` I saw there were 3 dips used (25, 1000 and 1008) but I have no idea why they are enabled or how to disable them

**Comment by Geod24** [comment]
Is your project open source ? Vibe.d is not compatible with DIP1000. The changes to get there are not trivial (e.g. breaking change in Phobos).

**Comment by WebFreak001** [comment]
yes it's here: https://gitlab.com/WebFreak001/osu-open-rooms-web/

**Comment by Geod24** [comment]
A quick looks tells me that the dependency chain is:
- https://gitlab.com/WebFreak001/osu-open-rooms-web/-/blob/93e2fd67d1bb8dd50b3e8007aab6471a732a7b21/dub.sdl#L4
- https://github.com/ikod/cachetools/blob/3b042ec80da18f3ebad3e8c885200712ecd4248b/dub.json#L6-L8
- https://github.com/atilaneves/automem/blob/8f61747f437b7624ad4b44085e9525fc143a9e6c/dub.sdl#L10

There's also a dependency to `unit-threaded` which probably has those on by default as well.

**Comment by WebFreak001** [comment]
oh wow I wouldn't have expected the dips to go down the dependency chain - at least I pushed updates to all my libraries to make them DIP1000 compatible now lol

Thanks, in that case I can simply change the configuration for that dependency which luckily has a "nodips" configuration.
