### ISSUE TITLE
TaskFiberQueue.insert functions are not `@safe`

### ISSUE THREAD

**Issue by dkorpel** [vibe-d/vibe-core#288]
In task.d there's this code:
```D
void insertFront(TaskFiber task)
{
	// ...
	task.m_queue = &this;
	// ...
}
```
Same for `insertBack` and `insertBackPred` . This compiles because of an accepts-invalid bug, but it should give errors:

```
source/vibe/core/task.d(1113,16): Error: reference to local variable `this` assigned to non-scope `task.m_queue`
source/vibe/core/task.d(1130,16): Error: reference to local variable `this` assigned to non-scope `task.m_queue`
source/vibe/core/task.d(1154,18): Error: reference to local variable `this` assigned to non-scope `task.m_queue`
```
After all, `TaskFiberQueue` can be a local variable, in which case the `TaskFiber` (which is a `class`) stores a stack pointer that can easily outlive the stackframe. This is blocking https://github.com/dlang/dmd/pull/12812

Since `TaskFiberQueue` is `private`, it could be marked `@trusted` when it's manually ensured that a public-facing `TaskFiber` never has a pointer to a stack-allocated `TaskFiberQueue`.

**Comment by s-ludwig** [comment]
`@trusted` is the way to go here. There is a single instance of `TaskFiberQueue` per thread (TLS global), which makes it memory correct, but definitely not `@safe`.
