### ISSUE TITLE
listenTCP Example for persistent tcp connections

### ISSUE THREAD

**Issue by anton-dutov** [vibe-d/vibe-core#30]
Any "idiomatic" example using listenTCP for persistent connections?

**Comment by s-ludwig** [comment]
What exactly do you mean by "persistent" in this case? Should the connection just automatically reconnect, or something in conjunction with multiple connections (e.g. `ConnectionPool` that is used for database connections). Or something higher level?

**Comment by Marenz** [comment]
I suggest we close this for now. If eventually a response arrives we can always reopen it.

**Comment by Marenz** [comment]
@anton-dutov well, I meant you ;) s-ludwig asked for a clarification of your question :)
