### ISSUE TITLE
Broken documentation on `UDPConnection.send`

### ISSUE THREAD

**Issue by Geod24** [vibe-d/vibe-core#300]
https://vibed.org/api/vibe.core.net/UDPConnection.send

What I see ATM:
<img width="1146" alt="Screen Shot 2021-10-26 at 15 46 13" src="https://user-images.githubusercontent.com/2180215/138823082-5fa8a943-53cb-422c-ac37-982fc24382d7.png">

What I expect to see:
https://github.com/vibe-d/vibe-core/blob/7833e425403c3804054b0bd16eacbf71fc7a28f4/source/vibe/core/net.d#L1058

**Comment by s-ludwig** [comment]
Appears to have been fixed by some update:
![image](https://user-images.githubusercontent.com/1645969/189374118-1f6956fe-6a64-45f6-a9be-11421595738c.png)
