### ISSUE TITLE
setupWorkerThreads does not work

### ISSUE THREAD

**Issue by Kozzi11** [vibe-d/vibe-core#35]
When I use libevent configuration for vibe-d:core. Everything works ok, but with vibe-core not.

void main()
{
    setupWorkerThreads(6);
    logInfo("%s", workerThreadCount); // print six with libevent, but zero with vibe-core
	runWorkerTaskDist(&runServer);
	runApplication();
}

**Comment by s-ludwig** [comment]
The problem was actually two-fold:
- `workerThreadCount` wasn't adjusted for the refactored worker task implementation and always returned zero
- `setupWorkerThreads` always used the number of logical cores instead of the number provided manually.

I'll also add a test for this.
