### ISSUE TITLE
Connect to Unix Domain Socket using vibe.core library (e.g. dbus on Linux)

### ISSUE THREAD

**Issue by electricface** [vibe-d/vibe-core#380]
I am trying to establish a connection to a Unix Domain Socket on a Linux system, specifically the dbus socket located at /run/user/1000/bus. I would like to use the vibe.core library for this purpose.
Does anyone know how to write code?

**Comment by s-ludwig** [comment]
It should work by setting up a `NetworkAddress` appropriately:

```D
NetworkAddress addr;
addr.family = AF_UNIX;
sockaddr_un* s = addr.sockAddrUnix();
s.sun_family = AF_UNIX;
strcpy(cast(char*)s.sun_path.ptr, "/run/user/1000/bus");
```

and then using `connectTCP` or `connectUDP` (don't mind the names...), depending on whether this is a stream or a datagram oriented socket.
