### ISSUE TITLE
Monotonic clock instead of SysTime for loopWithTimeout?

### ISSUE THREAD

**Issue by Boris-Barboris** [vibe-d/vibe-core#39]
https://github.com/vibe-d/vibe-core/blob/master/source/vibe/core/net.d#L675

Hello again! Do you remember any special case reasoning around the choice of timing mechanism for this function? I'm positive that a timeout violation during clock switch is not a good thing.

Do you mind if I change it to MonoTime?

**Comment by s-ludwig** [comment]
Do you mean due to daylight saving time? UTC does not have that, so there shouldn't be an issue here AFAICS, also `SysTime` stores the time stamp as a linear entity internally anyway. I'm not sure whether `MonoTime` has some other advantage, such as performance (precision is limited by the wait function anyway), but it would in general be a valid alternative.

**Comment by Boris-Barboris** [comment]
>also SysTime stores the time stamp as a linear entity internally anyway
I'm not sure I'm geting you here. I'm talking about manual or delayed to post boot system clock alterations. They do alter SysTime output, don't they?

**Comment by s-ludwig** [comment]
Ah okay, that's true. I guess it depends on for what the timer is being used whether that would be a good or a bad thing. For some component that sends out e-mails at specific points in time this would actually be very desirable behavior, while for simple delays it would obviously be bad.

BTW, I'm currently really thinking about the timer code in eventcore, which also uses `SysTime`. For the network timeout code I don't see an argument against `MonoTime`.

Maybe for timers the best bet would be to provide two different approaches - timeout based on `Duration` and timeout based on absolute `SysTime`, where the `SysTime` based API is mapped to the `MonoTime` one with appropriate adjustement facilities.
