### ISSUE TITLE
Using new vibe-core starts hundreds of threads

### ISSUE THREAD

**Issue by Kozzi11** [vibe-d/vibe-core#6]
I am trying to update TechEmpower FrameworkBenchmarks for vibed. And when I test it with new vibe-core it doesnt work properly. Using vibe-core seems to start a new thread for every request.

So test will fail because of out of memory error

**Comment by s-ludwig** [comment]
I tried to reproduce this with a similar test application (bench-http-server using `HTTPServerIOption.distribute` and also with `runWorkerTaskDist`) on Linux/x64, but there were just 5 threads as expected. Memory use stayed at about 23 MB during the benchmark. Do you know during which of the tests it runs out of memory?

**Comment by Kozzi11** [comment]
Ok, I am only able to reproduce this with FrameworkBenchmarks in their vagrant VirtualBox machine with their test framework. I findout it does not depends on any test, you even does not need to run any test, it happens after starting vibed app.

It is wierd when I start it from commandline it works ok, but when framework (tfb --sleep 10 --test vibed --duration 5 --threads 4 --type json) is used error occured. It does not matter which test you try or which args you change

**Comment by Kozzi11** [comment]
Btw. on my local machine it works somehow ok, but it does not scale around threads, it seems like it does ignore `HTTPServerIOption.distribute`

**Comment by Kozzi11** [comment]
Maybe they send some wiers signal(s) to process?, or they somehowe emulate wierd enviroment

**Comment by s-ludwig** [comment]
Could it be that they are emulating a large number of CPU cores? At least that would make sense when they use the same VM for their real benchmark. I've switched the benchmark to use `runWorkerTaskDist` now, instead of `HTTPServerOption.distribute`. The matching `TCPListenOptions.distribute` is indeed not implemented for `vibe-core` and it probably won't due to its thread-unsafe nature.

**Comment by Kozzi11** [comment]
that makes sense

**Comment by s-ludwig** [comment]
Just tried and created two threads for me now within the Vagrant environment, so I guess this can be closed.

I also took the opportunity to investigate performance a bit and found that there are GC allocations in the basic event handling logic. Eliminating those will not be simple, but should greatly reduce GC lock contention in the benchmark.
