### ISSUE TITLE
Resource leak in createTimer

### ISSUE THREAD

**Issue by SirNickolas** [vibe-d/vibe-core#86]
```d
int main() nothrow @safe {
    import core.time;
    import vibe.core.core;

    runTask({
        while (true) {
            auto timer = setTimer(2.seconds, { assert(false); }, true);
            sleep(1.msecs);
            timer.stop();
        }
    });
    return runEventLoop();
}
```

This keeps consuming memory. After a minute, the program crashes with SIGABRT. Having glanced at the [source](https://github.com/vibe-d/vibe-core/blob/fae7d3e93d00d9636632aa0acf9ebc19ed9f4a34/source/vibe/core/core.d#L783), I suspect the leak to be caused by a task continuing to wait for a (stopped) timer indefinitely.

**Comment by wilzbach** [comment]
Isn't everything that happens after an AssertError undefined behavior?
Can you also reproduce this without the `assert(0)`?

**Comment by SirNickolas** [comment]
I put that `assert` to only notice that the callback isn't executed. Timer's period is `2.seconds`, and it is cancelled after `1.msecs`.

**Comment by wilzbach** [comment]
Sorry only glanced briefly on it from my phone. Please ignore my comment then.
